# -*- coding: utf-8 -*-
"""Real Data - msml612-demo.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1E75Wu5sD0f95CIicMxz3hJwsEefY2okE

# MSML612 Group Project: Transformer Forecasting of TESS Light Curves
**MLE boilerplate (Kush)** - persistence / LSTM / transformer, shared eval harness, transit-sensitivity breakdown.

Runs standalone on synthetic light curves. To switch to real data, replace one line in Cell 2 with `data = load_from_ronoy("tess_windows.npz")` once Ronoy's file matches the contract below. Outputs at the end (results table, checkpoint, predictions npz) go to Vivek for figures and writeup.

### Cell 1: Setup + Config
**Config.** One dataclass controls everything, so a run is reproducible from the printed config alone. `Runtime > Change runtime type > GPU` in Colab.
"""

import math, numpy as np, torch, torch.nn as nn
import matplotlib
matplotlib.use("Agg")  # headless: no display on compute nodes
import matplotlib.pyplot as plt
from dataclasses import dataclass
from torch.utils.data import TensorDataset, DataLoader

import os as _os

torch.manual_seed(612); np.random.seed(612)
DEVICE = "cuda" if torch.cuda.is_available() else "cpu"
# The cluster's pytorch module was missing libcudnn_ops_train.so, which breaks the
# cuDNN LSTM path. Left off by default; set CUDNN=1 to try it once a module with a
# complete cuDNN is loaded, since it is a large speedup for the LSTM on real data.
torch.backends.cudnn.enabled = _os.environ.get("CUDNN") == "1"

@dataclass
class Config:
    input_len: int = 256      # past flux points fed to the model
    target_len: int = 32      # future points to forecast
    d_model: int = 64
    n_heads: int = 4
    n_layers: int = 3
    ff_dim: int = 128
    dropout: float = 0.1
    lstm_hidden: int = 64
    batch_size: int = 128
    lr: float = 1e-3
    max_epochs: int = 40
    patience: int = 5
    use_huber: bool = False   # flip on if flux outliers dominate MSE
    flux_scale: float = 1e3   # train in (flux-1)*1e3 units; raw deltas ~1e-3 give tiny gradients

    @classmethod
    def from_env(cls):
        """Env overrides so a Slurm sweep never has to edit this file:

            sbatch --export=ALL,D_MODEL=128,N_LAYERS=6,MAX_EPOCHS=80 train.sh
        """
        kwargs = {}
        for field, cast in cls.__annotations__.items():
            raw = _os.environ.get(field.upper())
            if raw is None:
                continue
            kwargs[field] = (raw.lower() in ("1", "true", "yes")) if cast is bool else cast(raw)
        cfg = cls(**kwargs)
        if kwargs:
            print(f"config overrides from env: {kwargs}")
        return cfg

cfg = Config.from_env()
print(f"device={DEVICE}")
if DEVICE == "cuda":
    print(f"gpu={torch.cuda.get_device_name(0)} "
          f"mem={torch.cuda.get_device_properties(0).total_memory / 1e9:.1f}GB "
          f"cudnn={torch.backends.cudnn.enabled}")

# Executable driver runs only when TESS_RUN=1 (batch job). Plain `import tess`
# for the data-build step imports defs + cfg without training or plotting.
_RUN = _os.environ.get("TESS_RUN") == "1"
_os.makedirs("outputs", exist_ok=True) if _RUN else None


"""### Cell 2: Data contract (Ronoy handoff) + synthetic stand-in
**Data contract.** This is the Phase 0 handoff agreement with Ronoy, stated as code. The synthetic generator mimics detrended TESS flux: level ~1.0, stellar variability, Gaussian noise, periodic box-shaped transits including shallow dips.
"""

# CONTRACT: one .npz file with arrays
#   X             float32 [N, input_len]   past detrended_flux window
#   y             float32 [N, target_len]  next segment
#   tic_id        int64   [N]              for traceability
#   split         str     [N]              'train' | 'val' | 'test' split BY STAR
#   transit_depth float32 [N]              dip proxy inside target window

import os, sys, subprocess
import numpy as np

try:
    import lightkurve as lk
except ImportError:
    subprocess.check_call([
        sys.executable, "-m", "pip", "install", "-q",
        "lightkurve", "astroquery", "pandas", "tqdm"
    ])
    import lightkurve as lk

def load_from_ronoy(path):
    z = np.load(path, allow_pickle=True)
    return {k: z[k] for k in ["X", "y", "tic_id", "split", "transit_depth"]}

def make_tess_windows(
    out_path="tess_windows.npz",
    tic_ids=(261136679, 307210830, 410153553, 150428135,
             231663901, 25155310, 260128333, 425997655),
    max_products=2,
    max_windows_per_star=200,
    seed=612,
):
    rng = np.random.default_rng(seed)
    X_all, y_all, tic_all, depth_all = [], [], [], []

    for idx, tic_id in enumerate(tic_ids, 1):
        print(f"[{idx}/{len(tic_ids)}] TIC {tic_id}")

        search = lk.search_lightcurve(f"TIC {tic_id}", mission="TESS")
        if len(search) == 0:
            print("  skipped: no light curve found")
            continue

        search = search[:max_products]

        try:
            lcc = search.download_all(
                quality_bitmask="default",
                flux_column="pdcsap_flux"
            )
        except Exception:
            lcc = search.download_all(quality_bitmask="default")

        if lcc is None or len(lcc) == 0:
            print("  skipped: download failed")
            continue

        # stitch()'s default corrector_func also calls .normalize() internally, which is what
        # crashes under this cluster's astropy/lightkurve version mismatch. Pass a no-op
        # corrector so stitch() does not normalize; manual median-normalize below covers it.
        lc = lcc.stitch(corrector_func=lambda x: x).remove_nans().remove_outliers(sigma=8)
        flux = np.asarray(lc.flux.value, dtype=np.float32)
        flux = flux[np.isfinite(flux)]

        med = np.nanmedian(flux)
        if np.isfinite(med) and med != 0:
            flux = flux / med

        total_len = cfg.input_len + cfg.target_len
        X_star, y_star, tic_star, depth_star = [], [], [], []

        for s in range(0, len(flux) - total_len + 1, cfg.target_len):
            X = flux[s : s + cfg.input_len]
            y = flux[s + cfg.input_len : s + total_len]

            if X.shape[0] != cfg.input_len or y.shape[0] != cfg.target_len:
                continue
            if not np.isfinite(X).all() or not np.isfinite(y).all():
                continue

            baseline = float(np.nanmedian(np.concatenate([X, y])))
            transit_depth = max(0.0, baseline - float(np.nanmin(y)))

            X_star.append(X.astype(np.float32))
            y_star.append(y.astype(np.float32))
            tic_star.append(int(tic_id))
            depth_star.append(np.float32(transit_depth))

        if len(X_star) > max_windows_per_star:
            keep = np.sort(rng.choice(len(X_star), max_windows_per_star, replace=False))
            X_star = [X_star[i] for i in keep]
            y_star = [y_star[i] for i in keep]
            tic_star = [tic_star[i] for i in keep]
            depth_star = [depth_star[i] for i in keep]

        print(f"  kept {len(X_star)} windows")

        X_all.extend(X_star)
        y_all.extend(y_star)
        tic_all.extend(tic_star)
        depth_all.extend(depth_star)

    X = np.asarray(X_all, dtype=np.float32)
    y = np.asarray(y_all, dtype=np.float32)
    tic_id = np.asarray(tic_all, dtype=np.int64)
    transit_depth = np.asarray(depth_all, dtype=np.float32)

    stars = np.unique(tic_id)
    rng.shuffle(stars)

    n_train = max(1, int(0.70 * len(stars)))
    n_val = max(1, int(0.15 * len(stars)))

    train_stars = set(stars[:n_train])
    val_stars = set(stars[n_train : n_train + n_val])

    split = np.empty(len(tic_id), dtype="<U5")
    for i, star in enumerate(tic_id):
        if star in train_stars:
            split[i] = "train"
        elif star in val_stars:
            split[i] = "val"
        else:
            split[i] = "test"

    np.savez_compressed(
        out_path,
        X=X,
        y=y,
        tic_id=tic_id,
        split=split,
        transit_depth=transit_depth,
    )

    return load_from_ronoy(out_path)

if _RUN:
    # zaratan_handoff.py writes data/tess_windows.npz; the older local build wrote
    # it beside this script. DATA can override both for named runs such as run_two.
    npz_path = _os.environ.get("DATA")
    if npz_path and not os.path.exists(npz_path):
        raise FileNotFoundError(f"DATA points to missing handoff file: {npz_path}")
    if not npz_path:
        npz_path = next((p for p in ("data/tess_windows.npz", "tess_windows.npz")
                         if os.path.exists(p)), "tess_windows.npz")

    if os.path.exists(npz_path):
        print(f"loading handoff file: {npz_path}")
        data = load_from_ronoy(npz_path)
    else:
        data = make_tess_windows(npz_path)

    print({k: v.shape for k, v in data.items()})

"""### Cell 3: Sanity checks + loaders (Phase 0)
**Sanity checks + scaling.** Detrended flux sits at ~1.0 with deltas of ~1e-3, so raw MSE gradients are tiny. We train in `(flux - 1) * 1000` units and convert back for metrics. Leakage check enforces the split-by-star rule.
"""

def sanity_check(d):
    assert not np.isnan(d["X"]).any() and not np.isnan(d["y"]).any(), "NaNs present"
    for a, b in [("train", "val"), ("train", "test"), ("val", "test")]:
        overlap = set(d["tic_id"][d["split"] == a]) & set(d["tic_id"][d["split"] == b])
        assert not overlap, f"star leakage between {a}/{b}: {overlap}"
    assert d["X"].shape[1] == cfg.input_len and d["y"].shape[1] == cfg.target_len
    print("sanity checks passed:", {s: int((d["split"] == s).sum()) for s in ["train", "val", "test"]})

def to_model_units(a):   return (a - 1.0) * cfg.flux_scale   # center at 0, scale up
def from_model_units(a): return a / cfg.flux_scale + 1.0

def make_loader(d, split, shuffle=False):
    m = d["split"] == split
    ds = TensorDataset(torch.from_numpy(to_model_units(d["X"][m])),
                       torch.from_numpy(to_model_units(d["y"][m])))
    # num_workers stays 0: the whole split is already an in-memory tensor, so worker
    # processes would only add IPC cost — and they would re-import this module's
    # top-level driver. pin_memory still buys a faster host->device copy.
    return DataLoader(ds, batch_size=cfg.batch_size, shuffle=shuffle,
                      pin_memory=(DEVICE == "cuda"))

if _RUN:
    sanity_check(data)
    train_dl = make_loader(data, "train", shuffle=True)
    val_dl   = make_loader(data, "val")
    test_dl  = make_loader(data, "test")

"""### Cell 4: Models (persistence, LSTM, transformer)
**Models.** All learned models predict a *delta from the last observed value*, with zero-initialized heads, so they start exactly at the persistence baseline and can only improve from there. This matters a lot for near-flat light curves.
"""

# All learned models predict a DELTA from the last observed flux value.
# Detrended flux sits near 1.0, so persistence is a very strong floor; forecasting
# the residual means models spend capacity on structure (dips), not on the DC level.
class Persistence(nn.Module):
    """Floor baseline: repeat the last observed value across the forecast window."""
    def __init__(self, cfg): super().__init__(); self.T = cfg.target_len
    def forward(self, x): return x[:, -1:].repeat(1, self.T)

class LSTMForecaster(nn.Module):
    def __init__(self, cfg):
        super().__init__()
        self.lstm = nn.LSTM(1, cfg.lstm_hidden, num_layers=2, batch_first=True)
        self.head = nn.Linear(cfg.lstm_hidden, cfg.target_len)
        nn.init.zeros_(self.head.weight); nn.init.zeros_(self.head.bias)  # start at persistence
    def forward(self, x):
        out, _ = self.lstm(x.unsqueeze(-1))
        return x[:, -1:] + self.head(out[:, -1])  # forecast = last value + learned delta

class PositionalEncoding(nn.Module):
    def __init__(self, d_model, max_len=4096):
        super().__init__()
        pe = torch.zeros(max_len, d_model)
        pos = torch.arange(max_len).unsqueeze(1)
        div = torch.exp(torch.arange(0, d_model, 2) * (-math.log(10000.0) / d_model))
        pe[:, 0::2] = torch.sin(pos * div); pe[:, 1::2] = torch.cos(pos * div)
        self.register_buffer("pe", pe)
    def forward(self, x): return x + self.pe[: x.size(1)]

class TransformerForecaster(nn.Module):
    """Linear embed -> sinusoidal PE -> encoder stack -> mean pool -> regression head."""
    def __init__(self, cfg):
        super().__init__()
        self.embed = nn.Linear(1, cfg.d_model)
        self.pe = PositionalEncoding(cfg.d_model)
        layer = nn.TransformerEncoderLayer(cfg.d_model, cfg.n_heads, cfg.ff_dim,
                                           cfg.dropout, batch_first=True, norm_first=True)
        self.encoder = nn.TransformerEncoder(layer, cfg.n_layers)
        self.head = nn.Linear(cfg.d_model, cfg.target_len)
        nn.init.zeros_(self.head.weight); nn.init.zeros_(self.head.bias)  # start at persistence
    def forward(self, x):
        h = self.encoder(self.pe(self.embed(x.unsqueeze(-1))))
        return x[:, -1:] + self.head(h.mean(dim=1))  # forecast = last value + learned delta

if _RUN:
    for m in [Persistence(cfg), LSTMForecaster(cfg), TransformerForecaster(cfg)]:
        n = sum(p.numel() for p in m.parameters())
        print(f"{type(m).__name__:22s} params={n:,}")

"""### Cell 5: Training loop (AdamW, early stopping, grad clip)
**Training loop.** AdamW, gradient clipping, early stopping on val loss, best-checkpoint restore. `use_huber` flag in config if flux outliers dominate.
"""

def train(model, train_dl, val_dl, cfg, max_epochs=None, verbose=True, history=None):
    """Returns the best-val model. Pass `history` (a dict) to collect per-epoch
    train/val loss for evaluate.py's training-curve figure."""
    model.to(DEVICE)
    if not any(p.requires_grad for p in model.parameters()):
        return model  # persistence: nothing to train
    opt = torch.optim.AdamW(model.parameters(), lr=cfg.lr)
    loss_fn = nn.HuberLoss() if cfg.use_huber else nn.MSELoss()
    best_val, best_state, bad = float("inf"), None, 0
    for epoch in range(max_epochs or cfg.max_epochs):
        model.train()
        epoch_losses = []
        for xb, yb in train_dl:
            xb, yb = xb.to(DEVICE), yb.to(DEVICE)
            opt.zero_grad()
            loss = loss_fn(model(xb), yb)
            loss.backward()
            nn.utils.clip_grad_norm_(model.parameters(), 1.0)
            opt.step()
            epoch_losses.append(loss.item())
        model.eval()
        with torch.no_grad():
            vl = np.mean([loss_fn(model(x.to(DEVICE)), t.to(DEVICE)).item() for x, t in val_dl])
        if history is not None:
            history.setdefault("train", []).append(float(np.mean(epoch_losses)))
            history.setdefault("val", []).append(float(vl))
        if verbose: print(f"  epoch {epoch:02d} val_loss={vl:.3e}")
        if vl < best_val - 1e-9:
            best_val, best_state, bad = vl, {k: v.clone() for k, v in model.state_dict().items()}, 0
        else:
            bad += 1
            if bad >= cfg.patience: break
    model.load_state_dict(best_state)
    return model

"""### Cell 6: Eval harness — every model goes through this
**Eval harness.** Every model, baseline or not, goes through the identical predict/metrics/plot path, so numbers in the report are directly comparable.
"""

@torch.no_grad()
def predict(model, dl):
    model.eval().to(DEVICE)
    P, Y = [], []
    for xb, yb in dl:
        P.append(model(xb.to(DEVICE)).cpu()); Y.append(yb)
    return (from_model_units(torch.cat(P).numpy()),   # metrics reported in real flux units
            from_model_units(torch.cat(Y).numpy()))

def metrics(pred, true):
    return {"MAE": float(np.abs(pred - true).mean()),
            "RMSE": float(np.sqrt(((pred - true) ** 2).mean()))}

def plot_examples(pred, true, X, idxs, title=""):
    fig, axes = plt.subplots(1, len(idxs), figsize=(4 * len(idxs), 3), sharey=False)
    for ax, i in zip(np.atleast_1d(axes), idxs):
        L = cfg.input_len
        ax.plot(range(L), X[i], lw=0.7, color="gray", label="context")
        ax.plot(range(L, L + cfg.target_len), true[i], lw=1.5, label="true")
        ax.plot(range(L, L + cfg.target_len), pred[i], lw=1.5, ls="--", label="pred")
        ax.set_xlim(L - 80, L + cfg.target_len)
    axes.flat[0].legend(fontsize=8); fig.suptitle(title); plt.tight_layout(); fig.savefig(f"outputs/examples_{title.split(':')[0].strip().replace(' ','_')}.png", dpi=150, bbox_inches="tight"); plt.close(fig)

"""### Cell 7: Overfit-a-tiny-subset pipeline check (Phase 2 gate)
**Pipeline gate.** Overfit a 5-star subset before scaling. If val loss doesn't drop steadily here, the bug is in the pipeline, not the hyperparameters.
"""

if _RUN:
    if _os.environ.get("SKIP_TINY") == "1":
        print("skipping tiny-subset overfit check")
    else:
        tiny_stars = np.unique(data["tic_id"][data["split"] == "train"])[:5]
        tiny_m = np.isin(data["tic_id"], tiny_stars)
        tiny = {k: v[tiny_m] for k, v in data.items()}
        tiny_dl = DataLoader(TensorDataset(torch.from_numpy(tiny["X"]), torch.from_numpy(tiny["y"])),
                             batch_size=cfg.batch_size, shuffle=True)
        print("tiny-subset overfit check (val_loss should drop steadily):")
        _ = train(TransformerForecaster(cfg), tiny_dl, tiny_dl, cfg, max_epochs=8)

"""### Cell 8: Train all models, shared results table
**Main comparison.** Persistence sets the floor; LSTM answers whether the transformer is earning its complexity.
"""

if _RUN:
    models = {"persistence": Persistence(cfg),
              "lstm": LSTMForecaster(cfg),
              "transformer": TransformerForecaster(cfg)}
    results, histories = {}, {}
    for name, m in models.items():
        print(f"--- {name} ---")
        histories[name] = {}
        m = train(m, train_dl, val_dl, cfg, verbose=False, history=histories[name])
        pred, true = predict(m, test_dl)
        results[name] = (pred, true)
        print(f"{name:12s} {metrics(pred, true)}")

"""### Cell 9: Phase 4 — transit-sensitivity breakdown (the novelty claim)
**Phase 4: the novelty claim.** Error broken out by transit vs quiet windows, plus dip-floor error vs true transit depth: does forecasting stay sensitive to *shallow* dips where classifiers fail?
"""

if _RUN:
    test_m = data["split"] == "test"
    has_transit = data["transit_depth"][test_m] > 0
    print(f"test windows: {test_m.sum()} total, {has_transit.sum()} contain a transit dip")
    print(f"{'model':12s} {'MAE(all)':>10s} {'MAE(transit)':>13s} {'MAE(quiet)':>11s} {'RMSE(transit)':>14s}")
    rows = []
    for name, (pred, true) in results.items():
        r = {"model": name,
             "MAE_all": metrics(pred, true)["MAE"],
             "MAE_transit": metrics(pred[has_transit], true[has_transit])["MAE"],
             "MAE_quiet": metrics(pred[~has_transit], true[~has_transit])["MAE"],
             "RMSE_transit": metrics(pred[has_transit], true[has_transit])["RMSE"]}
        rows.append(r)
        print(f"{name:12s} {r['MAE_all']:>10.2e} {r['MAE_transit']:>13.2e} "
              f"{r['MAE_quiet']:>11.2e} {r['RMSE_transit']:>14.2e}")

    # depth-resolved error on transit windows: does the model see shallow dips?
    depths = data["transit_depth"][test_m][has_transit]
    pred_t, true_t = results["transformer"][0][has_transit], results["transformer"][1][has_transit]
    depth_err = np.abs((true_t.min(1) - pred_t.min(1)))  # error in predicted dip floor
    plt.figure(figsize=(4.5, 3))
    plt.scatter(depths, depth_err, s=8, alpha=0.5)
    plt.xlabel("true transit depth"); plt.ylabel("|dip-floor error|")
    plt.title("Transformer: shallow-dip sensitivity"); plt.tight_layout(); plt.savefig("outputs/shallow_dip_sensitivity.png", dpi=150, bbox_inches="tight"); plt.close()

"""### Cell 10: Qualitative plots + handoff to Vivek
**Qualitative plots + handoff.** Prediction-vs-truth on the deepest-dip test windows, then artifacts saved for Vivek.
"""

if _RUN:
    X_test = data["X"][test_m]
    dip_idxs = np.argsort(-data["transit_depth"][test_m])[:3]  # deepest-dip windows
    for name in ["persistence", "transformer"]:
        pred, true = results[name]
        plot_examples(pred, true, X_test, dip_idxs, title=f"{name}: transit windows")

    import csv, json
    with open("results_table.csv", "w", newline="") as f:
        w = csv.DictWriter(f, fieldnames=rows[0].keys()); w.writeheader(); w.writerows(rows)
    torch.save({"state_dict": models["transformer"].state_dict(), "config": vars(cfg)},
               "transformer_best.pt")

    # tic_id and X ride along so evaluate.py can do the per-star breakdown and draw
    # the context leading into each forecast; history feeds the training curves.
    np.savez("test_predictions.npz",
             **{f"pred_{k}": v[0] for k, v in results.items()},
             true=results["transformer"][1],
             transit_depth=data["transit_depth"][test_m],
             tic_id=data["tic_id"][test_m],
             X=X_test)
    with open("outputs/history.json", "w") as f:
        json.dump({k: v for k, v in histories.items() if v}, f)
    print("saved: results_table.csv, transformer_best.pt, test_predictions.npz, "
          "outputs/history.json")
    print("run `python evaluate.py` for the full metric suite and figures  ->  Vivek")
